version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:3000"                 # Host:Container
    depends_on:
      - db
    environment:
      - KEY=jhbjsagasdlkzxmdch892374anmsdad
      - APP_PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=test123
      - DB_DATABASE=notes
    networks:
      - notesnw
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=notes
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notesnw
    restart: always

volumes:
  mysql-data:

networks:
  notesnw:
